name: master_thesis
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates
  - certifi=2019.6.16
  - intel-openmp
  - libcxx
  - libcxxabi
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - openssl=1.1.1c
  - pandas=0.20.3
  - pip=19.1.1
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytz=2019.1
  - readline=7.0
  - sqlite=3.29.0
  - tk=8.6.8
  - wheel=0.33.4
  - xz=5.2.4
  - zlib=1.2.11
  - tensorflow-gpu = 1.11.0
  - cudatoolkit = 9.0
  - cudnn = 7.6.5
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - bunch==1.0.1
    - cloudpickle==1.2.1
    - cycler==0.10.0
    - dask==2.1.0
    - decorator==4.4.0
    - gast==0.2.2
    - grpcio==1.22.0
    - h5py==2.9.0
    - hdf5storage==0.1.15
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==3.1.1
    - networkx==2.3
    - numpy==1.15.0
    - pillow==6.1.0
    - protobuf==3.9.0
    - pyparsing==2.4.2
    - pywavelets==1.0.3
    - pyyaml==3.13
    - scikit-image==0.14.1
    - scipy==1.3.0
    - setuptools==39.1.0
    - six==1.12.0
    - tensorboard==1.11.0
    - termcolor==1.1.0
    - toolz==0.10.0
    - werkzeug==0.15.5

